### ISSUE TITLE
6.7.z branch

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/nailgun#713]
Issue for tracking 6.7.z branching in Nailgun. Once all items on list below are Done, we can branch off.

- [x] #611 - stalled, not a blocker for branching
- [x] #635 - stalled, not a blocker for branching
- [x] #637 - stalled, not a blocker for branching
- [x] #701 - stalled, no response from author, assuming not a blocker
- [x] #709 - merged
- [x] #710 - merged

**Comment by mirekdlugosz** [comment]
Branch created out of 490d97a2f34502ce0b9c437253b94f1f44ef7556
